/**
 * Country flag utilities for MFL player nationalities
 */

export const getCountryFlag = (country: string): string => {
  const countryToFlag: Record<string, string> = {
    // Major European Football Nations
    'FRANCE': '🇫🇷',
    'ENGLAND': '🇬🇧',
    'WALES': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    'SCOTLAND': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    'NORTHERN IRELAND': '🏴󠁧󠁢󠁮󠁩󠁲󠁿',
    'IRELAND': '🇮🇪',
    'REPUBLIC OF IRELAND': '🇮🇪',
    'SPAIN': '🇪🇸',
    'GERMANY': '🇩🇪',
    'ITALY': '🇮🇹',
    'PORTUGAL': '🇵🇹',
    'NETHERLANDS': '🇳🇱',
    'BELGIUM': '🇧🇪',
    'SWITZERLAND': '🇨🇭',
    'AUSTRIA': '🇦🇹',
    'DENMARK': '🇩🇰',
    'SWEDEN': '🇸🇪',
    'NORWAY': '🇳🇴',
    'FINLAND': '🇫🇮',
    'POLAND': '🇵🇱',
    'CZECH REPUBLIC': '🇨🇿',
    'CZECHIA': '🇨🇿',
    'SLOVAKIA': '🇸🇰',
    'HUNGARY': '🇭🇺',
    'ROMANIA': '🇷🇴',
    'BULGARIA': '🇧🇬',
    'CROATIA': '🇭🇷',
    'SERBIA': '🇷🇸',
    'BOSNIA AND HERZEGOVINA': '🇧🇦',
    'MONTENEGRO': '🇲🇪',
    'NORTH MACEDONIA': '🇲🇰',
    'ALBANIA': '🇦🇱',
    'GREECE': '🇬🇷',
    'TURKEY': '🇹🇷',
    'UKRAINE': '🇺🇦',
    'RUSSIA': '🇷🇺',
    'BELARUS': '🇧🇾',
    'LITHUANIA': '🇱🇹',
    'LATVIA': '🇱🇻',
    'ESTONIA': '🇪🇪',
    'MOLDOVA': '🇲🇩',
    'GEORGIA': '🇬🇪',
    'ARMENIA': '🇦🇲',
    'AZERBAIJAN': '🇦🇿',
    'CYPRUS': '🇨🇾',
    'MALTA': '🇲🇹',
    'ICELAND': '🇮🇸',
    'LUXEMBOURG': '🇱🇺',
    'LIECHTENSTEIN': '🇱🇮',
    'ANDORRA': '🇦🇩',
    'SAN MARINO': '🇸🇲',
    'VATICAN CITY': '🇻🇦',
    'MONACO': '🇲🇨',
    
    // Major South American Football Nations
    'BRAZIL': '🇧🇷',
    'ARGENTINA': '🇦🇷',
    'URUGUAY': '🇺🇾',
    'PARAGUAY': '🇵🇾',
    'COLOMBIA': '🇨🇴',
    'CHILE': '🇨🇱',
    'PERU': '🇵🇪',
    'ECUADOR': '🇪🇨',
    'BOLIVIA': '🇧🇴',
    'VENEZUELA': '🇻🇪',
    'GUYANA': '🇬🇾',
    'SURINAME': '🇸🇷',
    'FRENCH GUIANA': '🇬🇫',
    
    // Major North American Football Nations
    'MEXICO': '🇲🇽',
    'UNITED STATES': '🇺🇸',
    'USA': '🇺🇸',
    'CANADA': '🇨🇦',
    'COSTA RICA': '🇨🇷',
    'PANAMA': '🇵🇦',
    'HONDURAS': '🇭🇳',
    'EL SALVADOR': '🇸🇻',
    'GUATEMALA': '🇬🇹',
    'NICARAGUA': '🇳🇮',
    'BELIZE': '🇧🇿',
    'JAMAICA': '🇯🇲',
    'TRINIDAD AND TOBAGO': '🇹🇹',
    'HAITI': '🇭🇹',
    'DOMINICAN REPUBLIC': '🇩🇴',
    'CUBA': '🇨🇺',
    'PUERTO RICO': '🇵🇷',
    
    // Major Asian Football Nations
    'JAPAN': '🇯🇵',
    'SOUTH KOREA': '🇰🇷',
    'KOREA REPUBLIC': '🇰🇷',
    'KOREA_REPUBLIC': '🇰🇷',
    'CHINA': '🇨🇳',
    'NORTH KOREA': '🇰🇵',
    'INDIA': '🇮🇳',
    'PAKISTAN': '🇵🇰',
    'BANGLADESH': '🇧🇩',
    'SRI LANKA': '🇱🇰',
    'NEPAL': '🇳🇵',
    'BHUTAN': '🇧🇹',
    'MALDIVES': '🇲🇻',
    'AFGHANISTAN': '🇦🇫',
    'IRAN': '🇮🇷',
    'IRAQ': '🇮🇶',
    'SAUDI ARABIA': '🇸🇦',
    'KUWAIT': '🇰🇼',
    'QATAR': '🇶🇦',
    'UNITED ARAB EMIRATES': '🇦🇪',
    'UAE': '🇦🇪',
    'OMAN': '🇴🇲',
    'YEMEN': '🇾🇪',
    'BAHRAIN': '🇧🇭',
    'JORDAN': '🇯🇴',
    'LEBANON': '🇱🇧',
    'SYRIA': '🇸🇾',
    'ISRAEL': '🇮🇱',
    'PALESTINE': '🇵🇸',
    'THAILAND': '🇹🇭',
    'VIETNAM': '🇻🇳',
    'CAMBODIA': '🇰🇭',
    'LAOS': '🇱🇦',
    'MYANMAR': '🇲🇲',
    'MALAYSIA': '🇲🇾',
    'SINGAPORE': '🇸🇬',
    'INDONESIA': '🇮🇩',
    'PHILIPPINES': '🇵🇭',
    'BRUNEI': '🇧🇳',
    'EAST TIMOR': '🇹🇱',
    'TIMOR LESTE': '🇹🇱',
    
    // Major African Football Nations
    'NIGERIA': '🇳🇬',
    'GHANA': '🇬🇭',
    'SENEGAL': '🇸🇳',
    'MOROCCO': '🇲🇦',
    'EGYPT': '🇪🇬',
    'TUNISIA': '🇹🇳',
    'ALGERIA': '🇩🇿',
    'IVORY COAST': '🇨🇮',
    'COTE D\'IVOIRE': '🇨🇮',
    'CAMEROON': '🇨🇲',
    'SOUTH AFRICA': '🇿🇦',
    'KENYA': '🇰🇪',
    'UGANDA': '🇺🇬',
    'TANZANIA': '🇹🇿',
    'ETHIOPIA': '🇪🇹',
    'SUDAN': '🇸🇩',
    'SOMALIA': '🇸🇴',
    'DJIBOUTI': '🇩🇯',
    'ERITREA': '🇪🇷',
    'BURUNDI': '🇧🇮',
    'RWANDA': '🇷🇼',
    'MALAWI': '🇲🇼',
    'ZAMBIA': '🇿🇲',
    'ZIMBABWE': '🇿🇼',
    'BOTSWANA': '🇧🇼',
    'NAMIBIA': '🇳🇦',
    'ANGOLA': '🇦🇴',
    'MOZAMBIQUE': '🇲🇿',
    'MADAGASCAR': '🇲🇬',
    'MAURITIUS': '🇲🇺',
    'SEYCHELLES': '🇸🇨',
    'COMOROS': '🇰🇲',
    'MAYOTTE': '🇾🇹',
    'REUNION': '🇷🇪',
    'GABON': '🇬🇦',
    'CONGO': '🇨🇬',
    'DEMOCRATIC REPUBLIC OF THE CONGO': '🇨🇩',
    'DR CONGO': '🇨🇩',
    'CENTRAL AFRICAN REPUBLIC': '🇨🇫',
    'CHAD': '🇹🇩',
    'NIGER': '🇳🇪',
    'MALI': '🇲🇱',
    'BURKINA FASO': '🇧🇫',
    'BENIN': '🇧🇯',
    'TOGO': '🇹🇬',
    'SIERRA LEONE': '🇸🇱',
    'LIBERIA': '🇱🇷',
    'GUINEA': '🇬🇳',
    'GUINEA BISSAU': '🇬🇼',
    'CAPE VERDE': '🇨🇻',
    'GAMBIA': '🇬🇲',
    'MAURITANIA': '🇲🇷',
    'WESTERN SAHARA': '🇪🇭',
    'EQUATORIAL GUINEA': '🇬🇶',
    'SAO TOME AND PRINCIPE': '🇸🇹',
    
    // Major Oceanian Football Nations
    'AUSTRALIA': '🇦🇺',
    'NEW ZEALAND': '🇳🇿',
    'PAPUA NEW GUINEA': '🇵🇬',
    'FIJI': '🇫🇯',
    'VANUATU': '🇻🇺',
    'NEW CALEDONIA': '🇳🇨',
    'SOLOMON ISLANDS': '🇸🇧',
    'SAMOA': '🇼🇸',
    'AMERICAN SAMOA': '🇦🇸',
    'TONGA': '🇹🇴',
    'COOK ISLANDS': '🇨🇰',
    'NIUE': '🇳🇺',
    'TOKELAU': '🇹🇰',
    'PALAU': '🇵🇼',
    'MICRONESIA': '🇫🇲',
    'MARSHALL ISLANDS': '🇲🇭',
    'KIRIBATI': '🇰🇮',
    'NAURU': '🇳🇷',
    'TUVALU': '🇹🇻',
    
      // Fallback
  'UNKNOWN': '🏳️',
};

// First try the exact match
const exactMatch = countryToFlag[country.toUpperCase()];
if (exactMatch) {
  return exactMatch;
}

// If no exact match, try with underscores replaced by spaces
const normalizedCountry = country.toUpperCase().replace(/_/g, ' ');
return countryToFlag[normalizedCountry] || '🏳️';
};

/**
 * Format country name for display by removing underscores and capitalizing properly
 */
export const formatCountryName = (country: string): string => {
  if (!country) return '';
  
  // Replace underscores with spaces and capitalize each word
  return country
    .replace(/_/g, ' ')
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ');
};
